- hosts: rpi
  name: Set up Kubernetes on the cluster
  pre_tasks:
    - ansible.builtin.include_tasks: "tasks/update.yml"
    - name: Add cgroup flags
      ansible.builtin.lineinfile:
        path: /boot/firmware/cmdline.txt
        backrefs: yes
        regexp: "^(.*rootwait.*)$"
        line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
      become: yes

    - name: Check if dphys-swapfile exists
      ansible.builtin.stat:
        path: /usr/sbin/dphys-swapfile
      register: dphys_swapfile

    - name: Disable swapfile
      ansible.builtin.command:
        cmd: "dphys-swapfile swapoff"
      when: dphys_swapfile.stat.exists
      become: yes

    - name: Uninstall swapfile
      ansible.builtin.command:
        cmd: "dphys-swapfile uninstall"
      when: dphys_swapfile.stat.exists
      become: yes

    - name: Remove swapfile package
      ansible.builtin.apt:
        name: dphys-swapfile
        state: absent
      when: dphys_swapfile.stat.exists
      become: yes

    - name: APT cleanup
      ansible.builtin.apt:
        autoremove: yes
      when: dphys_swapfile.stat.exists
      become: yes
  roles:
    - kubeadm
